### ISSUE TITLE
Problem running with npm run prod

### ISSUE THREAD

**Issue by SandeepSRathore** [mdshohelrana/full-stack-angular2-nodejs-mongodb#1]
While running app with npm run prod it returns error like : 

 module.js:540
[3]     throw err;
[3]     ^
[3]
[3] Error: Cannot find module './routes'
[3]     at Function.Module._resolveFilename (module.js:538:15)
[3]     at Function.Module._load (module.js:468:25)
[3]     at Module.require (module.js:587:17)
[3]     at require (internal/module.js:11:18)
[3]     at Object.<anonymous> (/home/ubuntu/mean-stack-master/dist/server/app.js:9:16)
[3]     at Module._compile (module.js:643:30)
[3]     at Object.Module._extensions..js (module.js:654:10)
[3]     at Module.load (module.js:556:32)
[3]     at tryModuleLoad (module.js:499:12)
[3]     at Function.Module._load (module.js:491:3)
[3]     at Function.Module.runMain (module.js:684:10)
[3]     at startup (bootstrap_node

Could you please look into it whether this is environment related issue or what.

**Comment by mdshohelrana** [comment]
Ok Let me check bro.

**Comment by mdshohelrana** [comment]
For development, use npm run dev
For production, use npm run prod

OK, Let me check bro.

**Comment by mdshohelrana** [comment]
@SandeepSRathore , Fixed this issues, Please pull this project again. Thanks

**Comment by SandeepSRathore** [comment]
Thanks for your quick response...it is working fine now.
